export const SPORTS = [
  {
    slug: "tenis",
    name: "Tennis",
    nameCs: "Tenis",
    subdomain: "tenis",
    description: "Tenisové kurty v České republice",
    icon: "🎾",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    lightBg: "bg-emerald-50",
    accent: "text-emerald-600",
    accentBg: "bg-emerald-600",
    accentHover: "hover:bg-emerald-700",
    ringColor: "ring-emerald-100",
    borderColor: "border-emerald-200",
    image: "/images/sports/tenis-hero.webp",
  },
  {
    slug: "squash",
    name: "Squash",
    nameCs: "Squash",
    subdomain: "squash",
    description: "Squashové kurty v České republice",
    icon: "🏸",
    color: "orange",
    gradient: "from-orange-500 to-amber-600",
    lightBg: "bg-orange-50",
    accent: "text-orange-600",
    accentBg: "bg-orange-600",
    accentHover: "hover:bg-orange-700",
    ringColor: "ring-orange-100",
    borderColor: "border-orange-200",
    image: "/images/sports/squash-hero.webp",
  },
  {
    slug: "badminton",
    name: "Badminton",
    nameCs: "Badminton",
    subdomain: "badminton",
    description: "Badmintonové kurty v České republice",
    icon: "🏸",
    color: "violet",
    gradient: "from-violet-500 to-purple-600",
    lightBg: "bg-violet-50",
    accent: "text-violet-600",
    accentBg: "bg-violet-600",
    accentHover: "hover:bg-violet-700",
    ringColor: "ring-violet-100",
    borderColor: "border-violet-200",
    image: "/images/sports/badminton-hero.webp",
  },
  {
    slug: "volejbal",
    name: "Volleyball",
    nameCs: "Volejbal",
    subdomain: "volejbal",
    description: "Volejbalové kurty v České republice",
    icon: "🏐",
    color: "sky",
    gradient: "from-sky-500 to-blue-600",
    lightBg: "bg-sky-50",
    accent: "text-sky-600",
    accentBg: "bg-sky-600",
    accentHover: "hover:bg-sky-700",
    ringColor: "ring-sky-100",
    borderColor: "border-sky-200",
    image: "/images/sports/volejbal-hero.webp",
  },
  {
    slug: "plavani",
    name: "Swimming",
    nameCs: "Plavání",
    subdomain: "plavani",
    description: "Plavecké bazény v České republice",
    icon: "🏊",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-500",
    lightBg: "bg-cyan-50",
    accent: "text-cyan-600",
    accentBg: "bg-cyan-600",
    accentHover: "hover:bg-cyan-700",
    ringColor: "ring-cyan-100",
    borderColor: "border-cyan-200",
    image: "/images/sports/plavani-hero.webp",
  },
  {
    slug: "golf",
    name: "Golf",
    nameCs: "Golf",
    subdomain: "golf",
    description: "Golfová hřiště, driving range, indoor golf",
    icon: "⛳",
    color: "green",
    gradient: "from-green-500 to-lime-600",
    lightBg: "bg-green-50",
    accent: "text-green-600",
    accentBg: "bg-green-600",
    accentHover: "hover:bg-green-700",
    ringColor: "ring-green-100",
    borderColor: "border-green-200",
    image: "/images/sports/golf-hero.webp",
  },
  {
    slug: "fitness",
    name: "Fitness",
    nameCs: "Fitness",
    subdomain: "fitness",
    description: "Fitness centra, posilovny, CrossFit boxy",
    icon: "🏋️",
    color: "red",
    gradient: "from-red-500 to-rose-600",
    lightBg: "bg-red-50",
    accent: "text-red-600",
    accentBg: "bg-red-600",
    accentHover: "hover:bg-red-700",
    ringColor: "ring-red-100",
    borderColor: "border-red-200",
    image: "/images/sports/fitness-hero.webp",
  },
  {
    slug: "padel",
    name: "Padel",
    nameCs: "Padel",
    subdomain: "padel",
    description: "Padelové kurty v České republice",
    icon: "🎾",
    color: "amber",
    gradient: "from-amber-500 to-yellow-600",
    lightBg: "bg-amber-50",
    accent: "text-amber-600",
    accentBg: "bg-amber-600",
    accentHover: "hover:bg-amber-700",
    ringColor: "ring-amber-100",
    borderColor: "border-amber-200",
    image: "/images/sports/padel-hero.webp",
  },
  {
    slug: "lezeni",
    name: "Climbing",
    nameCs: "Lezení",
    subdomain: "lezeni",
    description: "Lezecká centra, bouldery a lezecké stěny v ČR",
    icon: "🧗",
    color: "indigo",
    gradient: "from-indigo-500 to-blue-600",
    lightBg: "bg-indigo-50",
    accent: "text-indigo-600",
    accentBg: "bg-indigo-600",
    accentHover: "hover:bg-indigo-700",
    ringColor: "ring-indigo-100",
    borderColor: "border-indigo-200",
    image: "/images/sports/lezeni-hero.webp",
  },
  {
    slug: "ferraty",
    name: "Via Ferrata",
    nameCs: "Ferraty",
    subdomain: "ferraty",
    description: "Ferraty a zajištěné cesty v České republice",
    icon: "⛰️",
    color: "lime",
    gradient: "from-lime-500 to-green-600",
    lightBg: "bg-lime-50",
    accent: "text-lime-600",
    accentBg: "bg-lime-600",
    accentHover: "hover:bg-lime-700",
    ringColor: "ring-lime-100",
    borderColor: "border-lime-200",
    image: "/images/sports/ferraty-hero.webp",
  },
  // stolni-tenis and florbal hidden — launching late April (SIL-232)
  // bowling hidden until data is cleaned (SIL-67) — most records are unrelated businesses
] as const;

export type SportSlug = (typeof SPORTS)[number]["slug"];

export function getSportBySlug(slug: string) {
  return SPORTS.find((s) => s.slug === slug);
}

/** Sports where facilities cannot be claimed or upgraded to premium (SIL-232) */
const NON_CLAIMABLE_SPORTS = new Set<string>(["ferraty"]);

export function isSportClaimable(sportSlug: string): boolean {
  return !NON_CLAIMABLE_SPORTS.has(sportSlug);
}
